[project]
name = "precious-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.0",
    "openai-whisper>=20250625",
    "razdel>=0.5.0",
]
